import "@/styles/globals.css";
import "@/assets/fonts.css";
import { MyProvider } from "../contexts/myContext.js";
import { DataProvider } from "../contexts/dataContext.js";
import Head from "next/head.js";

import React from "react";
import App from "next/app";

export default class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;
    return (
      <MyProvider>
        <DataProvider>
          <Head>
            <title>BookLog App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/logo.png" />
          </Head>
          <Component {...pageProps} />
        </DataProvider>
      </MyProvider>
    );
  }
}

MyApp.layout = "previous";
