import "@/styles/globals.css";
import { MyProvider } from "../contexts/myContext.js";
import Head from "next/head.js";

import React from "react";
import App from "next/app";

/* export default function App({ Component, pageProps }) {
  return (
    <MyProvider>
      <Component {...pageProps} />
    </MyProvider>
  );
} */

export default class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;
    return (
      <MyProvider>
        <Head>
          <title>BookLog App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <Component {...pageProps} />
      </MyProvider>
    );
  }
}

MyApp.layout = "previous";
