import Head from "next/head";
import Navigation from "../components/Navigation";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>BookLog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation></Navigation>
      <Header title="BookLog App"></Header>
    </>
  );
}
